### PR TITLE
Support React Router V4 and V3

### LINKED ISSUE #127: Router redirect feature incompatible with React Router v4.0.0-beta.7
The latest release of React Router causes the 'use router for redirect if no redirectAction specified' feature to break.

From the [React Router release notes](https://github.com/ReactTraining/react-router/releases/tag/v4.0.0-beta.7)

> Split `context.router` into two parts: `context.history` and `context.route`

This causes [L126](https://github.com/mjrussell/redux-auth-wrapper/blob/4e0145bf55cabdd4597afa41241fd068ef640c99/src/index.js#L126) and [L130](https://github.com/mjrussell/redux-auth-wrapper/blob/4e0145bf55cabdd4597afa41241fd068ef640c99/src/index.js#L130) to error when using `redux-auth-wrapper` without a `redirectAction` and with `react-router v4.0.0-beta.7`

### PR DESCRIPTION
**Pull request by mjrussell**
Resolves #127 

I decided that it would be easier to maintain a single branch/version of redux-auth-wrapper and support both versions of React Router (v3 and v4). Hopefully the two versions don't diverge too much, but the code changes to the source of the wrapper were fairly minimal.

The more complicated changes occurred in the test suite, and figuring out how to run both React Router v3 and React Router v4 tests with (effectively) 100% coverage. I think I've got a decent solution and Travis' matrix tests make it pretty easy.

I'd like to update the documentation to note the version compatibility and provide an example before merging

### CODE REVIEW

**Comment by mjrussell** [comment]
If anyone wants to port either the basic example or the loading example to React Router v4 and submit a PR to this branch that would 👌 and help me get this in a little sooner. Please make a note if you want to tackle it. Otherwise I'll try to finish this up during the week. I'll handle the documentation updates

**Comment by shai32** [comment]
React Router v4 works only with React-Router-Redux v5, is the new version support that?

**Comment by mjrussell** [comment]
@shai32 redux-auth-wrapper doesn't really care about a redux-routing integration. As long as you can pass a `redirectAction` that follows the history spec then it should work. I haven't tried it myself though. So in principle, redux-auth-wrapper should support RRV3 (React-Router-Redux V4) and RRV4 (React-Router-Redux V5) all using the same version once this is merged

**Comment by mjrussell** [comment]
I can try to throw a sanity test in though in the RRV4 specific tests to be sure

**Comment by shai32** [comment]
@mjrussell Thanks for info.
Do you Recommend using React-Router-Redux with your package, or should I implement a simple redirectAction and thats it.

It will be nice it we had a full example with or without React-Router-Redux.

**Comment by mjrussell** [comment]
@shai32 Im a bit conflicted on whether to recommend users to include react-router-redux or not in their code. Personally, I do use it in my projects and find it generally useful, especially in tandem with some complex routing work I've done. I also prefer dispatching redux actions as opposed to using a global import for navigating with the browser.

However in the majority of projects I don't believe it is necessary and the maintainers of that library will tell you many times that you probably dont need the library at all either. I also think that  there may be better redux and history integrations in the future, so if you dont need it yet its probably better to limit your dependencies.

I plan on including at least one react router v4 example before merging and will probably not include react-router-redux to show an alternative

**Comment by mjrussell** [comment]
Quick update...I did create an RRV4 version of the loading example in fd655d6 however I didn't realize that query params have been removed (https://github.com/ReactTraining/react-router/issues/4842) and we need to manually serialize to/from the search. I think that was the in first RRV4 PR but since the tests passed I ignored it.

Definitely a bummer, I need to see if I can still make it compatible with both version. Then I'll update the tests once more and any changes to the example

**Comment by shai32** [comment]
@mjrussell  can I use the rr-v4 branch to start integrating your package, until an official version will be ready?

**Comment by mjrussell** [comment]
@shai32 I think I need to re-work the API...I dont see a way to easily support the new history API. I believe the simplest way might be to pass in history serializer/deserializer (similar but slightly different than `redirectAction`) and then provide some convenience exports for rrv3 / rrv4 which is really based on the history version.

The main issue right now is that the serialization is broken, you cant put query params on a location object (you can but the URL doesn't reflect it and it only works in browser history and is an unsupported ability). So if you integrate it the new branch and then provide a custom `redirectAction` that puts the query on the `search` (like [this](https://github.com/m-allanson/redux-auth-wrapper/blob/5614083e270a785bd5fbab0241d1198a1ea16f7c/src/index.js#L48)), it will be somewhat similar to the new implementation.

**Comment by newsiberian** [comment]
Hi, @mjrussell, thanks for such a great app. SSR support also should be different, right?

**Comment by mjrussell** [comment]
@newsiberian in what way? I'd be interested to hear you take on it since I dont use SSR myself. Since SSR doesn't appear to be supported in rrv4 I was hoping an onEnter static method in addition to react router v3 support would be enough.

**Comment by newsiberian** [comment]
Hi, I'm not sure, but it looks like, the new principals spinning around comparing `context.url`.

**Comment by shai32** [comment]
@newsiberian Do you have any plan to continue with this PR?

**Comment by mjrussell** [comment]
Im still planning on support RRV4, I've haven't had anytime to work on this and the changes are far more extensive than I initially thought. I have thought about it a lot though. Im hoping to get a reworked beta version out this weekend for people to comment on and try

**Comment by mjrussell** [comment]
Please provide your thoughts on #145. It seems to work quite well with react router v4

**Comment by mjrussell** [comment]
Closing in favor of #153

**Pull request closed without merging**
