### PR TITLE
update to use prop-types package

### PR DESCRIPTION
**Pull request by jruhland**
@mjrussell

### CODE REVIEW

**Comment by jruhland** [comment]
Any update on the chance of getting this merged and a corresponding version bump?

**Comment by mjrussell** [comment]
@jruhland yeah..sorry been focused on getting #145 done before tackling anything else as I have very limited time. Will look this over tonight try to release something for 1.x

**Comment by jruhland** [comment]
Thanks much :+1:!

**Comment by mjrussell** [comment]
@jruhland thanks for this!

**Comment by mjrussell** [comment]
Released in 1.1.0

**Pull request merged**
